apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchtower-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watchtower
  template:
    metadata:
      labels:
        app: watchtower
    spec:
      containers:
        - name: watchtower
          image: containrrr/watchtower
          imagePullPolicy: Always
          args:
            - --cleanup
            - --interval=3600
            # Add other Watchtower flags as needed
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
